### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by tyranron** [ReSpeak/tsclientlib#22]
Hi, guys! 👋  
It's almost a year since I'm succesfully using this library. Thank you so much for it, and for the all effort!

Would it be possible to release some intermediate 0.2 version? It's really a bit hard to catch up with you by raw commits.

Thanks!

**Comment by Flakebi** [comment]
Hi!

It’s definitely time for a 0.2 release. I try to keep the [changelog](https://github.com/ReSpeak/tsclientlib/blob/master/CHANGELOG.md) up to date to make it a little easier with the many breaking changes.
The one things, that is currently blocking, is that the `eax` version we need to use is not yet released on crates.io (they also changed something there, so I think tsclientlib is not building because dependencies are not found).
Is saw some pre-releases recently, so they might do a release soon anyway. I’ll poke them if I don’t see anything in the next weeks.

**Comment by tyranron** [comment]
@Flakebi I've managed to temporalily [fix the version like this](https://github.com/ALLATRA-IT/tsclientlib-rs/commit/b483a3aacc36f990a3ac39ec81d26c51de4f8d44), so it builds OK now.

However, for `cargo publish` we still need to wait and referer a crates.io release, I guess.

**Comment by Flakebi** [comment]
Thanks, I already pushed that ;)

**Comment by Flakebi** [comment]
tsclientlib 0.2 is finally done!

@0xpr03, I’ll create an issue to track breaking changes and ping you there.
