### ISSUE TITLE
Create Identity with exported TeamSpeak identity

### ISSUE THREAD

**Issue by skhalymon** [ReSpeak/tsclientlib#23]
Hi guys!

I'm curious where you get actually Identity Key. I've tried to get it from TeamSpeak by exporting through GUI and pass identity property from *.ini file. 

I'm getting the error `Any known methods to decode the key failed` with this:

```
Identity::new_from_str("42VeP4pQAky4r+nmCrlGAUCReG3ZW5zE3lAcHEDfiUae3oBcHJ1ekRvUyR1DS9fKXtIBmF8U1VxSR9UWm0ie2l0Q1NoVnZVVn58LBdjUDYJTixnZgZFIHtCN0IHfHxWNVx1JkZzeEJPTnJLUUloQUxSVlFqNjlDeWRnS0Y5UE5rdVJqMXdLczU2OXdnUHpwZTUyeFhERHVBTDk=")
```

In your In the [example key](https://github.com/ReSpeak/tsclientlib/blob/33678d401eef95f432bc23d02f0ca4d9575caed6/tsclientlib/examples/audio.rs#L60) it is different though. But It's not cleaner is it possible to get this key from TS identity or not. 

Thanks!

UPD

Actually, with your key, it doesn't work either. Maybe need to try the latest version

**Comment by Splamy** [comment]
The reason the example key is slightly different is because teampseak stores identities with `<counter> 'V' <base64-encoded-private-key>`, so in your case the `42` is the counter followed by the constant `V` and the private key.
I just pushed a fix (d85e08d6e4d088c9d19b9958578aaf7df9cbcbac) which should now just automatically parse this case an gives you the identity object with the private key and counter set.
