### ISSUE TITLE
Normalization of channel streams to same out level

### ISSUE THREAD

**Issue by skhalymon** [ReSpeak/tsclientlib#31]
Hey all!

In regular Teamspeak client, there is an option to specify the volume per each client. It's helpful when speakers use different microphones.

I'm curious how it's possible to achieve some normalization to a specified level across all clients in the channel. I know that each client is a separate stream, and we pass relevant data to `AudioHandler::handle_packet`. But currently have no idea how to normalize this data. Do you have some ideas? Thanks!

**Comment by Flakebi** [comment]
Hi,
I’d say loudness normalization is out of scope for tsclientlib itself.
One way this can probably be implemented is by measuring the loudness of each stream with something like [ebur128](https://docs.rs/ebur128) and then setting the volume in the AudioHandler accordingly (`AudioHandler::fill_buffer_with_proc` can be used to get each stream on its own) so that everything ends up with the same loudness.

**Comment by skhalymon** [comment]
Thank you, @Flakebi! I'll check it out!
